__author__ = 'fabio.lana'

var = {12462: {'name_clean': 'Djerem', 'name_orig': u'Djerem'},
       12463: {'name_clean': 'Faro_Et_Deo', 'name_orig': u'Faro - Et - De\u0301o'},
       12464: {'name_clean': 'Mayo_Banyo', 'name_orig': u'Mayo-Banyo'},
       12465: {'name_clean': 'Mbere', 'name_orig': u'Mbe\u0301re\u0301'},
       12466: {'name_clean': 'Vina', 'name_orig': u'Vina'},
       12467: {'name_clean': 'Haute_Sanaga', 'name_orig': u'Haute - Sanaga'},
       12468: {'name_clean': 'Lekie', 'name_orig': u'Le\u0301kie\u0301'},
       12469: {'name_clean': 'Mbam_Et_Inoubou', 'name_orig': u'Mbam - Et - Inoubou'},
       12470: {'name_clean': 'Mbam_Et_Kim', 'name_orig': u'Mbam - Et - Kim'},
       12471: {'name_clean': 'Mefou_Et_Afamba', 'name_orig': u'Me\u0301fou - Et - Afamba'},
       12472: {'name_clean': 'Mefou_Et_Akono', 'name_orig': u'Me\u0301fou - Et - Akono'},
       12473: {'name_clean': 'Mfoundi', 'name_orig': u'Mfoundi'},
       12474: {'name_clean': 'Nyong_Et_Kelle', 'name_orig': u'Nyong - Et - Ke\u0301lle\u0301'},
       12475: {'name_clean': 'Nyong_Et_Mfoumou', 'name_orig': u'Nyong - Et - Mfoumou'},
       12476: {'name_clean': 'Nyong_Et_Soo', 'name_orig': u"Nyong - Et - So'o"},
       12477: {'name_clean': 'Boumba_Et_Ngoko', 'name_orig': u'Boumba - Et - Ngoko'},
       12478: {'name_clean': 'Haut_Nyong', 'name_orig': u'Haut - Nyong'},
       12479: {'name_clean': 'Kadei', 'name_orig': u'Kadei\u0308'},
       12480: {'name_clean': 'Lom_Et_Djerem', 'name_orig': u'Lom - Et - Djerem'},
       12481: {'name_clean': 'Diamare', 'name_orig': u'Diamare\u0301'},
       12482: {'name_clean': 'Logone_Et_Chari', 'name_orig': u'Logone - Et - Chari'},
       12483: {'name_clean': 'Mayo_Danay', 'name_orig': u'Mayo-Danay'},
       12484: {'name_clean': 'Mayo_Kani', 'name_orig': u'Mayo-Kani'},
       12485: {'name_clean': 'Mayo_Sava', 'name_orig': u'Mayo-Sava'},
       12486: {'name_clean': 'Mayo_Tsanaga', 'name_orig': u'Mayo-Tsanaga'},
       12487: {'name_clean': 'Moungo', 'name_orig': u'Moungo'},
       12488: {'name_clean': 'Nkam', 'name_orig': u'Nkam'},
       12489: {'name_clean': 'Sanaga_Maritime', 'name_orig': u'Sanaga - Maritime'},
       12490: {'name_clean': 'Wouril', 'name_orig': u'Wouril'},
       12491: {'name_clean': 'Boyo', 'name_orig': u'Boyo'},
       12492: {'name_clean': 'Bui', 'name_orig': u'Bui'},
       12493: {'name_clean': 'Donga_Mantung', 'name_orig': u'Donga - Mantung'},
       12494: {'name_clean': 'Menchum', 'name_orig': u'Menchum'},
       12495: {'name_clean': 'Mezam', 'name_orig': u'Mezam'},
       12496: {'name_clean': 'Momo', 'name_orig': u'Momo'},
       12497: {'name_clean': 'Ngo_Ketunjia', 'name_orig': u'Ngo-Ketunjia'},
       12498: {'name_clean': 'Benoue', 'name_orig': u'Be\u0301noue'},
       12499: {'name_clean': 'Faro', 'name_orig': u'Faro'},
       12500: {'name_clean': 'Mayo_Louti', 'name_orig': u'Mayo-Louti'},
       12501: {'name_clean': 'Mayo_Rey', 'name_orig': u'Mayo - Rey'},
       12502: {'name_clean': 'Bamboutos', 'name_orig': u'Bamboutos'},
       12503: {'name_clean': 'Haut_Nkam', 'name_orig': u'Haut-Nkam'},
       12504: {'name_clean': 'Hauts_Plateaux', 'name_orig': u'Hauts-Plateaux'},
       12505: {'name_clean': 'Koung_Khi', 'name_orig': u'Koung-Khi'},
       12506: {'name_clean': 'Menoua', 'name_orig': u'Me\u0301noua'},
       12507: {'name_clean': 'Mifi', 'name_orig': u'Mifi'},
       12508: {'name_clean': 'Nde', 'name_orig': u'Nde'},
       12509: {'name_clean': 'Noun', 'name_orig': u'Noun'},
       12510: {'name_clean': 'Fako', 'name_orig': u'Fako'},
       12511: {'name_clean': 'KupeManenguba', 'name_orig': u'Kupe\u0301 Manenguba'},
       12512: {'name_clean': 'Lebialem', 'name_orig': u'Lebialem'},
       12513: {'name_clean': 'Manyu', 'name_orig': u'Manyu'},
       12514: {'name_clean': 'Meme', 'name_orig': u'Meme'},
       12515: {'name_clean': 'Ndian', 'name_orig': u'Ndian'},
       12516: {'name_clean': 'Dja_Et_Lobo', 'name_orig': u'Dja - Et - Lobo'},
       12517: {'name_clean': 'Mvila', 'name_orig': u'Mvila'},
       12518: {'name_clean': 'Ocean', 'name_orig': u'Oce\u0301an'},
       12519: {'name_clean': 'Vallee_Du_Ntem', 'name_orig': u'Valle\u0301e - Du - Ntem'}}

for chiave_area in var.iteritems():
    print chiave_area[0]
    print chiave_area[1]['name_clean']